# Generated by Django 5.0.6 on 2024-06-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitnessChallenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietCalculator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('sex', models.CharField(max_length=10)),
                ('activity', models.CharField(max_length=20)),
                ('goal', models.CharField(max_length=10)),
                ('bmr', models.FloatField(blank=True, null=True)),
                ('recommended_calories', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='product',
        ),
        migrations.DeleteModel(
            name='Diet',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
